# cgns path
cgns_file : "X:/iric_sample_data/python_workshop/02_raster/case0/Case1.cgn"

# nays2dh path
exe_path : 'X:/iric_sample_data/python_workshop/02_raster/nays2dh/nays2dh.exe'

# tif file for elevation as real
tif_zb : './tif_data/N35363E139093_N35264E139176_UM_DTM.tif'

# averaged cell number
ncell : 5

#0:ave, 1:max, 2:min
method : 0

# tif file for manning roughness as real
tif_sn : './tif_data/N35363E139093_N35264E139176_UM_DTM.tif'

# tif file for vegetation as integer
tif_vege : './tif_data/N35363E139093_N35264E139176_UM_DTM.tif'

# density, height
vege_param :
  [
    [0.0, 0.5],
    [0.1, 0.5],
    [0.2, 1.0],
    [0.3, 1.0],
    [0.4, 2.0],
    [0.5, 2.0],
    [0.6, 3.0],
    [0.7, 3.0],
    [0.8, 5.0],
    [0.9, 5.0],
    [1.0, 10.0]
  ]
